# Generated by Django 4.2.18 on 2026-03-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('published', 'Одобрено'), ('draft', 'На рассмотрении'), ('canceled', 'Отклонено')], default='draft'),
        ),
    ]
