# Generated by Django 4.2.18 on 2026-03-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0003_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bookmarked_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(choices=[('published', 'Одобрено'), ('pending', 'На рассмотрении'), ('canceled', 'Отклонено')], default='pending'),
        ),
        migrations.AlterField(
            model_name='siteerror',
            name='status',
            field=models.TextField(choices=[('pending', 'На рассмотрении'), ('solved', 'Решено')], default='pending'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
