# Generated by Django 4.2.18 on 2026-04-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_comment_bookmarked_by_remove_comment_liked_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteError',
        ),
    ]
