# Generated by Django 4.2.18 on 2026-03-14 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='Nothing', max_length=1000, null=True)),
                ('cat_title', models.CharField(max_length=255, unique=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(upload_to='categories/')),
                ('followers', models.ManyToManyField(blank=True, related_name='category_followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
